# Generated by Django 4.2 on 2025-02-24 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo', '0002_rename_category_shelf_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelf',
            name='tag',
            field=models.CharField(choices=[('未設定', '未設定'), ('タスク', 'タスク'), ('defaultINnote', 'ノート'), ('defaultINother', 'その他')], max_length=100),
        ),
    ]
